# Generated by Django 5.2.7 on 2025-10-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('role', models.IntegerField(choices=[(0, 'Admin'), (1, 'Guest'), (2, 'Author'), (3, 'Editor')], default=1)),
            ],
        ),
    ]
